# Site settings
title: Andrey Lobatch
email: andrey@lobat.ch
description: "Best Dad's Kick-ass Website"
baseurl: "http://andrey.lobat.ch"
#baseurl: ""
url: ""

# Default build settings
markdown: kramdown


# Andrey's build settings
permalink: /blog/:year/:i_month/:i_day/:title

# Sass directory
sass:
  sass_dir: stylesheets/_sass
